name: CI (GCC Matrix)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: [11, 12, 13]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies (CMake + GCC)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++-${{ matrix.gcc }} valgrind
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.gcc }} 100

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build -j$(nproc)

    - name: Run unit tests
      run: cd build && ./launch

  valgrind-check:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies (CMake + GCC + Valgrind)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ valgrind

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build . -j$(nproc)

    - name: Run memory check
      run: cd build && valgrind --error-exitcode=1 ./launch
